'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace Wpf_PivotGrid_CustomFieldSort_Example.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Wpf_PivotGrid_CustomFieldSort_Example.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Wpf_PivotGrid_CustomFieldSort_Example.Properties.Settings())), Wpf_PivotGrid_CustomFieldSort_Example.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return Wpf_PivotGrid_CustomFieldSort_Example.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
